after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 25

default-root-container-layout = "tiles"

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-ctrl-left = ['join-with left', 'mode main']
alt-ctrl-down = ['join-with down', 'mode main']
alt-ctrl-up = ['join-with up', 'mode main']
alt-ctrl-right = ['join-with right', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -200'
alt-shift-equal = 'resize smart +200'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1:general'
alt-2 = 'workspace 2:coding'
alt-3 = 'workspace 3:extra'
alt-4 = 'workspace 4:teams'
alt-5 = 'workspace 5:slack'
alt-6 = 'workspace 6:spotify'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1:general'
alt-shift-2 = 'move-node-to-workspace 2:coding'
alt-shift-3 = 'move-node-to-workspace 3:extra'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Auto move windows to workspaces
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1:general'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 2:coding'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace 2:coding'

[[on-window-detected]]
if.app-id = 'ai.perplexity.mac'
run = 'move-node-to-workspace 3:extra'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 4:teams'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 5:slack'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 6:spotify'
