# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
< $directory$git_branch$git_status$character
'''

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = ">"
error_symbol = "[>](bold red)"

[git_status]
deleted = "D"
modified = "M"
staged = "S"
untracked = "U"
ahead= "⇡"
behind= "⇣"

format = "\\[$deleted$modified$staged$untracked$ahead_behind\\] "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
